### ISSUE TITLE
Date not displaying

### ISSUE THREAD

**Issue by lupa18** [rhansen/ep_adminpads2#1]
First, thanks for this fork !
I can see pads and delete them, but "Last edited" column is empty. 

thanks !

**Comment by anoymouserver** [comment]
This seems to be caused by [`getLastEdited`](https://github.com/ether/etherpad-lite/blob/e6251687bf6f0d773ef5cd8883465d67e18f4816/src/node/db/API.js#L460-L474) which is async and because of that the `resultObject` is a pending Promise.
https://github.com/rhansen/ep_adminpads2/blob/1cbef74775b912b60e65f6a6520cf94a036272eb/index.js#L77-L78
However, the surrounding forEach does not seem to support async/await. So adding await before the call does not work.

[`padUsersCount`](https://github.com/ether/etherpad-lite/blob/37abb21a55671614c444ad63d9c66155074a2dbf/src/node/handler/PadMessageHandler.js#L1476-L1483) on the other hand is a normal function and simply return an object.
https://github.com/rhansen/ep_adminpads2/blob/1cbef74775b912b60e65f6a6520cf94a036272eb/index.js#L79-L80

Unfortunately my JavaScript knowledge is not good enough to fix this by myself.

**Comment by HarryBleckert** [comment]
I am also happy that you created this fork, least I can see and delete pads again.
However, on my Etherpad 1.8.4 instance, "Last edited" column is also empty.
Remark: Etherpad is connected to PostgreSQL 12.3 DB Server.

**Comment by Mondrethos** [comment]
I am also having this issue. Last Edited is empty.

**Comment by Mondrethos** [comment]
By the way, ep_adminpads3 fixes this issue. Look for it in your plugings list in your etherpad admin area. Enjoy!

**Comment by rhansen** [comment]
Apologies for not responding—for some reason GitHub didn't notify me about this issue. :frowning_face: I'll take a look at the changes made in ep_adminpads3 and cherry-pick the appropriate fixes.

**Comment by rhansen** [comment]
v0.0.5 has been published with a fix to this issue.

Please let me know if you notice any other issues. I configured GitHub to send me notifications if a new issue is opened so I should be more responsive in the future. (Today I learned that GitHub automatically sets forks to "unwatched". You have to manually enable watching. :angry:)
